name: Model validation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyparsing lark-parser==0.12.0 networkx requests sqlalchemy sqlalchemy-utils
        mkdir -p ~/.local/lib/python3.10/site-packages
        wget https://s3.amazonaws.com/ifcopenshell-builds/ifcopenshell-python-310-v0.7.0-fc50bdd-linux64.zip
        unzip ifcopenshell-python-310-v0.7.0-fc50bdd-linux64.zip -d ~/.local/lib/python3.10/site-packages
        wget -O ~/.local/lib/python3.10/site-packages/ifcopenshell/entity_instance.py https://raw.githubusercontent.com/IfcOpenShell/IfcOpenShell/2dc4bbf8cdee1db784808c89930020eb7c17a7ba/src/ifcopenshell-python/ifcopenshell/entity_instance.py
    - name: Model validation
      run: |
        ./validate.sh
